authors = ["Andrei Zhabinski <andrei.zhabinski@pandadoc.com>"]
name = "Espresso"
uuid = "f3367e62-6a9b-11e8-3ca8-97e71e02b39c"
version = "0.5.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
